In [37]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import json
from sklearn.preprocessing import LabelEncoder

In [38]:
data_raw = "P4AI_BT1.csv"
data = pd.read_csv(data_raw)
data

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           NaN          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          NaN     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          NaN           5.0          1.9  Virginica
147           NaN          NaN           5.2          2.0  Virginica
148           NaN          3.4           NaN          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [39]:
df1 = data.copy() # sao chép dữ liệu giúp thuận tiện cho việc sửa lỗi

In [40]:
df1['sepal.length'].fillna(round(df1['sepal.length'].mean()), inplace=True)
df1['sepal.width'].fillna(round(df1['sepal.width'].mean()), inplace=True)
df1['petal.length'].fillna(round(df1['petal.length'].mean()), inplace=True)
df1['petal.width'].fillna(round(df1['petal.width'].mean()), inplace=True)
# df1['variety'].fillna(df1['variety'].mode()[0], inplace = True)

In [41]:
df1

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           4.0          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          1.0     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          3.0           5.0          1.9  Virginica
147           6.0          3.0           5.2          2.0  Virginica
148           6.0          3.4           4.0          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [42]:
df2 = df1[df1['variety'].notna()]
df3 = df1[df1['variety'].isna()]

In [43]:
df2

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           4.0          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          1.0     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          3.0           5.0          1.9  Virginica
147           6.0          3.0           5.2          2.0  Virginica
148           6.0          3.4           4.0          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[135 rows x 5 columns]

In [45]:
df3
df_pre = df3.copy()

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df2.iloc[:, :-1], df2.iloc[:, -1], test_size=0.2, random_state=42
)

In [47]:
X_train.shape

(108, 4)

In [48]:
X_test.shape

(27, 4)

# KNN

In [49]:
from sklearn import neighbors
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [50]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 10, weights = 'distance', metric='euclidean')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("KNN accuracy: ", accuracy_score(y_test, y_pred))
print("KNN f1 score: ", f1_score(y_test, y_pred, average='weighted'))
print("KNN confusion matrix: ")
print(confusion_matrix(y_test, y_pred))

KNN accuracy:  0.8518518518518519
KNN f1 score:  0.8546870914020672
KNN confusion matrix:
[[11  1  0]
 [ 0  7  0]
 [ 0  3  5]]

In [51]:
y_pred = clf.predict(df_pre.drop(['variety'], axis=1))
y_pred

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Versicolor',
       'Versicolor', 'Virginica', 'Versicolor', 'Versicolor',
       'Versicolor', 'Virginica', 'Virginica', 'Virginica', 'Virginica'],
      dtype=object)

In [52]:
df3['predicted_variety'] = y_pred
df3

C:\Users\Dell service\AppData\Local\Temp\ipykernel_3060\2710887449.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['predicted_variety'] = y_pred

,sepal.length,sepal.width,petal.length,petal.width,variety,predicted_variety
9,4.9,3.1,1.5,0.1,NaN,Setosa
11,4.8,3.0,1.6,0.2,NaN,Setosa
17,5.1,3.5,1.4,0.3,NaN,Setosa
27,5.2,3.5,1.5,0.2,NaN,Setosa
33,5.5,4.2,1.4,0.2,NaN,Setosa
50,7.0,3.2,4.7,1.4,NaN,Versicolor
68,6.2,2.2,4.5,1.5,NaN,Versicolor
70,5.9,3.2,4.8,1.8,NaN,Virginica
71,6.1,2.8,4.0,1.3,NaN,Versicolor
81,5.5,2.4,3.7,1.0,NaN,Versicolor
91,6.1,3.0,4.6,1.4,NaN,Versicolor
115,6.4,3.2,5.3,2.3,NaN,Virginica
118,7.7,2.6,6.9,2.3,NaN,Virginica
122,7.7,2.8,6.7,2.0,NaN,Virginica
144,6.7,3.0,5.7,2.5,NaN,Virginica

# Logistic Regression

In [53]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [54]:
regressor = LogisticRegression()
regressor.fit(X_train, y_train)

# predict
predictions = regressor.predict(X_test)
# evaluate
print("LR classification accuracy", accuracy_score(y_test, predictions))

# matrix confusion
cm = confusion_matrix(y_test, predictions)
print(cm)

# f1 score
print("LR f1 score", f1_score(y_test, predictions, average="macro"))

LR classification accuracy 0.8888888888888888
[[12  0  0]
 [ 0  7  0]
 [ 0  3  5]]
LR f1 score 0.8642533936651584

C:\Users\Dell service\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [55]:
df4 = df_pre.copy()

In [56]:
predictions = regressor.predict(df_pre.drop(['variety'], axis=1))

In [57]:
df4['predicted_variety'] = predictions
df4

,sepal.length,sepal.width,petal.length,petal.width,variety,predicted_variety
9,4.9,3.1,1.5,0.1,NaN,Setosa
11,4.8,3.0,1.6,0.2,NaN,Setosa
17,5.1,3.5,1.4,0.3,NaN,Setosa
27,5.2,3.5,1.5,0.2,NaN,Setosa
33,5.5,4.2,1.4,0.2,NaN,Setosa
50,7.0,3.2,4.7,1.4,NaN,Versicolor
68,6.2,2.2,4.5,1.5,NaN,Versicolor
70,5.9,3.2,4.8,1.8,NaN,Virginica
71,6.1,2.8,4.0,1.3,NaN,Versicolor
81,5.5,2.4,3.7,1.0,NaN,Versicolor
91,6.1,3.0,4.6,1.4,NaN,Versicolor
115,6.4,3.2,5.3,2.3,NaN,Virginica
118,7.7,2.6,6.9,2.3,NaN,Virginica
122,7.7,2.8,6.7,2.0,NaN,Virginica
144,6.7,3.0,5.7,2.5,NaN,Virginica

# SVM

In [58]:
# svm to classify
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score


clf = SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("SVM accuracy: ", accuracy_score(y_test, y_pred))
print("SVM f1 score: ", f1_score(y_test, y_pred, average='weighted'))
print("SVM confusion matrix: ")
print(confusion_matrix(y_test, y_pred))

SVM accuracy:  0.8518518518518519
SVM f1 score:  0.8436213991769547
SVM confusion matrix:
[[12  0  0]
 [ 0  7  0]
 [ 0  4  4]]

In [61]:
df5 = df_pre.copy()
predictions=clf.predict(df_pre.drop(['variety'], axis=1))

In [62]:
df5['predicted_variety'] = predictions
df5

,sepal.length,sepal.width,petal.length,petal.width,variety,predicted_variety
9,4.9,3.1,1.5,0.1,NaN,Setosa
11,4.8,3.0,1.6,0.2,NaN,Setosa
17,5.1,3.5,1.4,0.3,NaN,Setosa
27,5.2,3.5,1.5,0.2,NaN,Setosa
33,5.5,4.2,1.4,0.2,NaN,Setosa
50,7.0,3.2,4.7,1.4,NaN,Versicolor
68,6.2,2.2,4.5,1.5,NaN,Versicolor
70,5.9,3.2,4.8,1.8,NaN,Virginica
71,6.1,2.8,4.0,1.3,NaN,Versicolor
81,5.5,2.4,3.7,1.0,NaN,Versicolor
91,6.1,3.0,4.6,1.4,NaN,Versicolor
115,6.4,3.2,5.3,2.3,NaN,Virginica
118,7.7,2.6,6.9,2.3,NaN,Virginica
122,7.7,2.8,6.7,2.0,NaN,Virginica
144,6.7,3.0,5.7,2.5,NaN,Virginica

turning hyperparameter for svm

In [64]:
from sklearn.model_selection import GridSearchCV

# defining parameter range
param_grid = {'C': [0.1, 1, 10],
                'gamma': [1, 0.1, 0.01],
                'kernel': ['rbf', 'linear', 'poly']}

grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)

# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.864 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.952 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.905 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.864 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.955 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.818 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.952 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.857 total time=   0.0s
[CV 1/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.955 total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.955 total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.955 total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=1, kernel=poly;, score=1.000 total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.905 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.909 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.818 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.818 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.952 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.810 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.864 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.955 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.818 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.952 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.857 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.864 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.955 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.909 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=1.000 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.905 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.545 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.318 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.318 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.714 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.571 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.864 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.955 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.818 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.952 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.857 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.409 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.636 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.545 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.571 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.429 total time=   0.0s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.905 total time=   0.0s
[CV 1/5] END .......C=1, gamma=1, kernel=linear;, score=0.864 total time=   0.0s
[CV 2/5] END .......C=1, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END .......C=1, gamma=1, kernel=linear;, score=0.864 total time=   0.0s
[CV 4/5] END .......C=1, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END .......C=1, gamma=1, kernel=linear;, score=0.857 total time=   0.0s
[CV 1/5] END .........C=1, gamma=1, kernel=poly;, score=0.955 total time=   0.0s
[CV 2/5] END .........C=1, gamma=1, kernel=poly;, score=1.000 total time=   0.0s
[CV 3/5] END .........C=1, gamma=1, kernel=poly;, score=0.955 total time=   0.0s
[CV 4/5] END .........C=1, gamma=1, kernel=poly;, score=0.952 total time=   0.0s
[CV 5/5] END .........C=1, gamma=1, kernel=poly;, score=0.905 total time=   0.0s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.864 total time=   0.0s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.864 total time=   0.0s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.952 total time=   0.0s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.857 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.864 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.864 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.857 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.909 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.1, kernel=poly;, score=1.000 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.955 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.1, kernel=poly;, score=1.000 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.905 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.909 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.909 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.773 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.905 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.810 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.864 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.01, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.864 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.01, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.857 total time=   0.0s
[CV 1/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.864 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.909 total time=   0.0s
[CV 3/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.773 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.952 total time=   0.0s
[CV 5/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.714 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.905 total time=   0.0s
[CV 1/5] END ......C=10, gamma=1, kernel=linear;, score=0.864 total time=   0.0s
[CV 2/5] END ......C=10, gamma=1, kernel=linear;, score=0.955 total time=   0.0s
[CV 3/5] END ......C=10, gamma=1, kernel=linear;, score=0.955 total time=   0.0s
[CV 4/5] END ......C=10, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END ......C=10, gamma=1, kernel=linear;, score=0.905 total time=   0.0s
[CV 1/5] END ........C=10, gamma=1, kernel=poly;, score=0.955 total time=   0.0s
[CV 2/5] END ........C=10, gamma=1, kernel=poly;, score=1.000 total time=   0.0s
[CV 3/5] END ........C=10, gamma=1, kernel=poly;, score=0.955 total time=   0.0s
[CV 4/5] END ........C=10, gamma=1, kernel=poly;, score=0.952 total time=   0.0s
[CV 5/5] END ........C=10, gamma=1, kernel=poly;, score=0.905 total time=   0.0s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.909 total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.955 total time=   0.0s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.905 total time=   0.0s
[CV 1/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.864 total time=   0.0s
[CV 2/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.955 total time=   0.0s
[CV 3/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.955 total time=   0.0s
[CV 4/5] END ....C=10, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.905 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.955 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.1, kernel=poly;, score=1.000 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.955 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.1, kernel=poly;, score=1.000 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.905 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.864 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.955 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.864 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.952 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.857 total time=   0.0s
[CV 1/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.864 total time=   0.0s
[CV 2/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.955 total time=   0.0s
[CV 3/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.955 total time=   0.0s
[CV 4/5] END ...C=10, gamma=0.01, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.905 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.864 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.955 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.864 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.952 total time=   0.0s

[CV 5/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.762 total time=   0.0s

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10], 'gamma': [1, 0.1, 0.01],
                         'kernel': ['rbf', 'linear', 'poly']},
             verbose=3)

In [65]:
# print best parameter after tuning
print(grid.best_params_)
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)
# print accuracy score
print("SVM accuracy: ", accuracy_score(y_test, grid.predict(X_test)))
print("SVM f1 score: ", f1_score(y_test, grid.predict(X_test), average='weighted'))
print("SVM confusion matrix: ")
print(confusion_matrix(y_test, grid.predict(X_test)))

{'C': 1, 'gamma': 1, 'kernel': 'rbf'}
SVC(C=1, gamma=1)
SVM accuracy:  0.9629629629629629
SVM f1 score:  0.9629629629629629
SVM confusion matrix:
[[12  0  0]
 [ 0  7  0]
 [ 0  1  7]]

In [66]:
df6 = df_pre.copy()
predictions=clf.predict(df_pre.drop(['variety'], axis=1))

In [67]:
df6['predicted_variety'] = predictions
df6

,sepal.length,sepal.width,petal.length,petal.width,variety,predicted_variety
9,4.9,3.1,1.5,0.1,NaN,Setosa
11,4.8,3.0,1.6,0.2,NaN,Setosa
17,5.1,3.5,1.4,0.3,NaN,Setosa
27,5.2,3.5,1.5,0.2,NaN,Setosa
33,5.5,4.2,1.4,0.2,NaN,Setosa
50,7.0,3.2,4.7,1.4,NaN,Versicolor
68,6.2,2.2,4.5,1.5,NaN,Versicolor
70,5.9,3.2,4.8,1.8,NaN,Virginica
71,6.1,2.8,4.0,1.3,NaN,Versicolor
81,5.5,2.4,3.7,1.0,NaN,Versicolor
91,6.1,3.0,4.6,1.4,NaN,Versicolor
115,6.4,3.2,5.3,2.3,NaN,Virginica
118,7.7,2.6,6.9,2.3,NaN,Virginica
122,7.7,2.8,6.7,2.0,NaN,Virginica
144,6.7,3.0,5.7,2.5,NaN,Virginica

# Random forests

In [69]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [70]:
clf = RandomForestClassifier(n_estimators=100, random_state=0)

# train model
clf.fit(X_train, y_train)

# predict
y_pred = clf.predict(X_test)

# evaluate
print("RF accuracy: ", accuracy_score(y_test, y_pred))
print("RF f1 score: ", f1_score(y_test, y_pred, average='weighted'))
print("RF confusion matrix: ")
print(confusion_matrix(y_test, y_pred))

RF accuracy:  1.0
RF f1 score:  1.0
RF confusion matrix:
[[12  0  0]
 [ 0  7  0]
 [ 0  0  8]]

In [71]:
df7 = df_pre.copy()
predictions=clf.predict(df_pre.drop(['variety'], axis=1))

In [72]:
df7['predicted_variety'] = predictions
df7

,sepal.length,sepal.width,petal.length,petal.width,variety,predicted_variety
9,4.9,3.1,1.5,0.1,NaN,Setosa
11,4.8,3.0,1.6,0.2,NaN,Setosa
17,5.1,3.5,1.4,0.3,NaN,Setosa
27,5.2,3.5,1.5,0.2,NaN,Setosa
33,5.5,4.2,1.4,0.2,NaN,Setosa
50,7.0,3.2,4.7,1.4,NaN,Versicolor
68,6.2,2.2,4.5,1.5,NaN,Versicolor
70,5.9,3.2,4.8,1.8,NaN,Virginica
71,6.1,2.8,4.0,1.3,NaN,Versicolor
81,5.5,2.4,3.7,1.0,NaN,Versicolor
91,6.1,3.0,4.6,1.4,NaN,Versicolor
115,6.4,3.2,5.3,2.3,NaN,Virginica
118,7.7,2.6,6.9,2.3,NaN,Virginica
122,7.7,2.8,6.7,2.0,NaN,Virginica
144,6.7,3.0,5.7,2.5,NaN,Virginica

hyperparameter tuning

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

# Number of trees in random forest
n_estimators = [100,200,300]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
                'max_features': max_features,
                'min_samples_split': min_samples_split}

# Random search of parameters, using 3 fold cross validation,
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = clf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)

# Fit the random search model
rf_random.fit(X_train, y_train)

In [ ]:
print(rf_random.best_params_)
# print how our model looks after hyper-parameter tuning
print(rf_random.best_estimator_)
# print accuracy score
print("RF accuracy: ", accuracy_score(y_test, rf_random.predict(X_test)))
print("RF f1 score: ", f1_score(y_test, rf_random.predict(X_test), average='weighted'))
print("RF confusion matrix: ")
print(confusion_matrix(y_test, rf_random.predict(X_test)))

In [73]:
df8 = df_pre.copy()
predictions=clf.predict(df_pre.drop(['variety'], axis=1))

In [74]:
df8['predicted_variety'] = predictions
df8

,sepal.length,sepal.width,petal.length,petal.width,variety,predicted_variety
9,4.9,3.1,1.5,0.1,NaN,Setosa
11,4.8,3.0,1.6,0.2,NaN,Setosa
17,5.1,3.5,1.4,0.3,NaN,Setosa
27,5.2,3.5,1.5,0.2,NaN,Setosa
33,5.5,4.2,1.4,0.2,NaN,Setosa
50,7.0,3.2,4.7,1.4,NaN,Versicolor
68,6.2,2.2,4.5,1.5,NaN,Versicolor
70,5.9,3.2,4.8,1.8,NaN,Virginica
71,6.1,2.8,4.0,1.3,NaN,Versicolor
81,5.5,2.4,3.7,1.0,NaN,Versicolor
91,6.1,3.0,4.6,1.4,NaN,Versicolor
115,6.4,3.2,5.3,2.3,NaN,Virginica
118,7.7,2.6,6.9,2.3,NaN,Virginica
122,7.7,2.8,6.7,2.0,NaN,Virginica
144,6.7,3.0,5.7,2.5,NaN,Virginica